"""Added BlogPost model

Revision ID: 5fbe37267bd3
Revises: c7b8682387a9
Create Date: 2024-09-05 16:09:45.603537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbe37267bd3'
down_revision = 'c7b8682387a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        # Skip dropping the constraint since SQLite may not have an explicit name for it
        if op.get_bind().dialect.name != 'sqlite':
            batch_op.drop_constraint('fk_blog_post_user_id', type_='foreignkey')  # Safe handling
        batch_op.drop_column('date_posted')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('date_posted', sa.DATETIME(), nullable=True))
        if op.get_bind().dialect.name != 'sqlite':
            batch_op.create_foreign_key('fk_blog_post_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('date_created')
    # ### end Alembic commands ###



    # ### end Alembic commands ###
