"""Add technologies and link fields to Project model

Revision ID: f6be415523e2
Revises: f5cd5e196ea1
Create Date: 2024-09-05 07:59:34.315546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6be415523e2'
down_revision = 'f5cd5e196ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('technologies', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('link', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        # Removing drop_constraint line since it doesn't exist
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        # Add the foreign key constraint back if it existed
        batch_op.create_foreign_key('fk_project_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('date_created')
        batch_op.drop_column('link')
        batch_op.drop_column('technologies')

    # ### end Alembic commands ###
